### PR TITLE
fixed https://github.com/NuGet/Home/issues/1125

### PR DESCRIPTION
**Pull request by zhili1208**
the root cause for this bug is pass tools folder path as intallPath to init.ps.
the fix is passing right package folder path to init.ps

### CODE REVIEW

**Comment by zhili1208** [comment]
@yishaigalatzer @deepakaravindr

**Comment by emgarten** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
@zhili1208, I believe we have certain functional tests for install.ps1 which verifies that the installPath and scriptPath are passed properly. Could you please use them to add similar functional tests for init.ps1 as well?

**Comment by yishaigalatzer** [comment]
@zhili1208 why is this still open?

**Comment by zhili1208** [comment]
this bug only happens during Powershell console initialization, so function test can't hit this bug, only UI can hit this. we might can add a test to manual verification

**Comment by deepakaravindr** [comment]
@zhili1208 

Init.ps1 is executed for every package not just during powershell initialization. And, one could test this bug fix using powershell functional tests. Adding tests as we fix these bugs are gonna help avoid regressions in the future. Please add tests for this. A separate PR is fine, given that you have already checked-in the fix

**Comment by zhili1208** [comment]
@deepakaravindr Please look at this PR, you misunderstood the issue here. this bug is in Powershell initialization and not in VSScriptExecutor. So if you open the powershell, then install the package, VSScriptExecutor run init.ps, you never hit this bug. only when you never open powershell before and Open UI, click install package, it will install the package and initialize the powershell, during that initialization, it's trying to run init.ps, it will fail. Then how Powershell functional test can hit this bug

**Comment by deepakaravindr** [comment]
Cool! Makes sense

**Pull request closed without merging**
