### PR TITLE
Set UserAgent.UserAgentString to use

### PR DESCRIPTION
**Pull request by deepakaravindr**
UserAgent.CreateUserAgentStringForVisualStudio(.

Related to https://github.com/NuGet/Home/issues/929

@yishaigalatzer @emgarten @pranavkm @feiling @zhili1208 @johnataylor

### CODE REVIEW

**Comment by feiling** [comment]
:shipit:

**Comment by pranavkm** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
Merged with https://github.com/NuGet/NuGet.VisualStudioExtension/commit/26d1567d3505290c807138dc63f165460ed43f7a

**Pull request closed without merging**
