### PR TITLE
Adding OriginalPackageConfig to contexts

### PR DESCRIPTION
**Pull request by emgarten**
A very minor change to update package contexts.

https://github.com/NuGet/Home/issues/1130

//cc @deepakaravindr @MeniZalzman @zhili1208 @yishaigalatzer

### CODE REVIEW

**Comment by MeniZalzman** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
Looks good, why do we have to repeat the property in two contexts? I would expect it to be set once

Sent from my Windows Phone

**Comment by emgarten** [comment]
@yishaigalatzer It was added on the INuGetProjectContext interface, so the contexts here need to implement it

**Comment by deepakaravindr** [comment]
:shipit:

**Comment by yishaigalatzer** [comment]
Sounds good

Sent from my Windows Phone

**Pull request closed without merging**
